export const UI_SAGA_GET_PRODUCT_LIST = 'UI_SAGA_GET_PRODUCT_LIST';
export const SA_RE_PRODUCT_LIST_RECEIVED = 'SA_RE_PRODUCT_LIST_RECEIVED';

export const UI_SA_GET_PRODUCT_DETAIL = 'UI_SA_GET_PRODUCT_DETAIL';
export const SA_RE_PRODUCT_DETAIL_RECEIVED = 'SA_RE_PRODUCT_DETAIL_RECEIVED';

export const GET_SUGGESTED_PRODUCT = 'GET_SUGGESTED_PRODUCT';
export const REMOVE_SUGGESTED_PRODUCT = 'REMOVE_SUGGESTED_PRODUCT';


