export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_SUGGESTED_PRODUCT = 'GET_SUGGESTED_PRODUCT';
export const REMOVE_SUGGESTED_PRODUCT = 'REMOVE_SUGGESTED_PRODUCT';


